"""Periodicidad

Revision ID: 2543540c2e65
Revises: 840ac39d73a3
Create Date: 2026-05-26 18:01:54.657295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2543540c2e65'
down_revision: Union[str, Sequence[str], None] = '840ac39d73a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('periodicity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'periodicity')
    # ### end Alembic commands ###
