"""SIN ENUMS

Revision ID: 43bdbd2b8895
Revises: 2543540c2e65
Create Date: 2026-05-26 18:14:32.203807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43bdbd2b8895'
down_revision: Union[str, Sequence[str], None] = '2543540c2e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'type',
               existing_type=postgresql.ENUM('OFICIAL', 'PROPUESTA', 'BLOQUEO', name='eventtype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('events', 'status',
               existing_type=postgresql.ENUM('PENDIENTE', 'CONFIRMADO', 'CANCELADO', name='eventstatus'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDIENTE', 'CONFIRMADO', 'CANCELADO', name='eventstatus'),
               existing_nullable=True)
    op.alter_column('events', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('OFICIAL', 'PROPUESTA', 'BLOQUEO', name='eventtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
