"""Reset a Strings

Revision ID: 4cc676bd1069
Revises: 
Create Date: 2026-05-26 18:40:39.471144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc676bd1069'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_votes', sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('event_votes', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event_votes', sa.Column('flag_disabled', sa.Boolean(), nullable=False))
    op.add_column('event_votes', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event_votes', 'users', ['created_by'], ['id'])
    op.add_column('events', sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('flag_disabled', sa.Boolean(), nullable=False))
    op.add_column('events', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('flag_disabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'flag_disabled')
    op.drop_column('users', 'last_modified')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'created_by')
    op.drop_column('events', 'flag_disabled')
    op.drop_column('events', 'last_modified')
    op.drop_column('events', 'date_creation')
    op.drop_constraint(None, 'event_votes', type_='foreignkey')
    op.drop_column('event_votes', 'created_by')
    op.drop_column('event_votes', 'flag_disabled')
    op.drop_column('event_votes', 'last_modified')
    op.drop_column('event_votes', 'date_creation')
    # ### end Alembic commands ###
