"""Creacion inicial de todo el ecosistema Hub y Musica

Revision ID: 521ba72c979e
Revises: 
Create Date: 2026-05-26 16:36:45.939422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521ba72c979e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id_album', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_album'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_table('concept_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id_album', sa.Integer(), nullable=True),
    sa.Column('id_song', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_album'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['id_song'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_ideas_id'), 'concept_ideas', ['id'], unique=False)
    op.create_table('post_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id_album', sa.Integer(), nullable=True),
    sa.Column('id_song', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_album'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['id_song'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_ideas_id'), 'post_ideas', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('chords', sa.Text(), nullable=True),
    sa.Column('time_signature', sa.String(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('id_song', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_song'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('id_song', sa.Integer(), nullable=True),
    sa.Column('id_section', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_section'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['id_song'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_id'), 'recordings', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('reply_to', sa.Integer(), nullable=True),
    sa.Column('id_post_idea', sa.Integer(), nullable=True),
    sa.Column('id_concept_idea', sa.Integer(), nullable=True),
    sa.Column('id_song', sa.Integer(), nullable=True),
    sa.Column('id_recording', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_concept_idea'], ['concept_ideas.id'], ),
    sa.ForeignKeyConstraint(['id_post_idea'], ['post_ideas.id'], ),
    sa.ForeignKeyConstraint(['id_recording'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['id_song'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['reply_to'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_recordings_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_post_ideas_id'), table_name='post_ideas')
    op.drop_table('post_ideas')
    op.drop_index(op.f('ix_concept_ideas_id'), table_name='concept_ideas')
    op.drop_table('concept_ideas')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
