"""Colores y descripcion en eventos

Revision ID: 840ac39d73a3
Revises: eb171e37eeb6
Create Date: 2026-05-26 18:01:25.919395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840ac39d73a3'
down_revision: Union[str, Sequence[str], None] = 'eb171e37eeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('color', sa.String(), nullable=True))
    op.add_column('events', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'description')
    op.drop_column('events', 'color')
    # ### end Alembic commands ###
