"""add key en section

Revision ID: d006a0e19b03
Revises: fcbba02bbec2
Create Date: 2026-07-01 16:03:14.582406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd006a0e19b03'
down_revision: Union[str, Sequence[str], None] = 'fcbba02bbec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'key')
    # ### end Alembic commands ###
