"""Añadida tabla users y autoría en todo el ecosistema

Revision ID: eb171e37eeb6
Revises: 521ba72c979e
Create Date: 2026-05-26 16:44:08.799101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb171e37eeb6'
down_revision: Union[str, Sequence[str], None] = '521ba72c979e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('albums', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'albums', 'users', ['created_by'], ['id'])
    op.add_column('comments', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['id_user'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['created_by'], ['id'])
    op.add_column('concept_ideas', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'concept_ideas', 'users', ['created_by'], ['id'])
    op.alter_column('event_votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'event_votes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['owner_id'], ['id'])
    op.add_column('post_ideas', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post_ideas', 'users', ['created_by'], ['id'])
    op.add_column('recordings', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recordings', 'users', ['created_by'], ['id'])
    op.add_column('sections', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sections', 'users', ['created_by'], ['id'])
    op.add_column('songs', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'songs', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'created_by')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_column('sections', 'created_by')
    op.drop_constraint(None, 'recordings', type_='foreignkey')
    op.drop_column('recordings', 'created_by')
    op.drop_constraint(None, 'post_ideas', type_='foreignkey')
    op.drop_column('post_ideas', 'created_by')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'event_votes', type_='foreignkey')
    op.alter_column('event_votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'concept_ideas', type_='foreignkey')
    op.drop_column('concept_ideas', 'created_by')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'created_by')
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'created_by')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
