"""add position

Revision ID: ee75a7a01819
Revises: d006a0e19b03
Create Date: 2026-07-10 00:07:17.721726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee75a7a01819'
down_revision: Union[str, Sequence[str], None] = 'd006a0e19b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'position')
    op.drop_column('sections', 'position')
    # ### end Alembic commands ###
